/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
	31337: {
		Albums: {
			address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
			abi: [
				{
					inputs: [
						{
							internalType: "string",
							name: "_name",
							type: "string"
						},
						{
							internalType: "string",
							name: "_artist",
							type: "string"
						},
						{
							internalType: "string",
							name: "_imageCID",
							type: "string"
						}
					],
					name: "addAlbum",
					outputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					stateMutability: "nonpayable",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "uint256",
							name: "_albumId",
							type: "uint256"
						},
						{
							internalType: "uint256",
							name: "_songId",
							type: "uint256"
						}
					],
					name: "addSongToAlbum",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					name: "albums",
					outputs: [
						{
							internalType: "uint256",
							name: "id",
							type: "uint256"
						},
						{
							internalType: "string",
							name: "name",
							type: "string"
						},
						{
							internalType: "string",
							name: "artist",
							type: "string"
						},
						{
							internalType: "string",
							name: "imageCID",
							type: "string"
						}
					],
					stateMutability: "view",
					type: "function"
				}
			],
			inheritedFunctions: {},
			deployedOnBlock: 3
		},
		Songs: {
			address: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
			abi: [
				{
					inputs: [
						{
							internalType: "string",
							name: "_name",
							type: "string"
						},
						{
							internalType: "string",
							name: "_audioCID",
							type: "string"
						}
					],
					name: "addSong",
					outputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					stateMutability: "nonpayable",
					type: "function"
				},
				{
					inputs: [],
					name: "getAllSongs",
					outputs: [
						{
							components: [
								{
									internalType: "uint256",
									name: "id",
									type: "uint256"
								},
								{
									internalType: "string",
									name: "name",
									type: "string"
								},
								{
									internalType: "string",
									name: "audioCID",
									type: "string"
								}
							],
							internalType: "struct Songs.Song[]",
							name: "",
							type: "tuple[]"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [],
					name: "getTotalSongs",
					outputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					name: "songs",
					outputs: [
						{
							internalType: "uint256",
							name: "id",
							type: "uint256"
						},
						{
							internalType: "string",
							name: "name",
							type: "string"
						},
						{
							internalType: "string",
							name: "audioCID",
							type: "string"
						}
					],
					stateMutability: "view",
					type: "function"
				}
			],
			inheritedFunctions: {},
			deployedOnBlock: 5
		},
		Wavecoin: {
			address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
			abi: [
				{
					inputs: [],
					stateMutability: "nonpayable",
					type: "constructor"
				},
				{
					inputs: [],
					name: "ECDSAInvalidSignature",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "uint256",
							name: "length",
							type: "uint256"
						}
					],
					name: "ECDSAInvalidSignatureLength",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "bytes32",
							name: "s",
							type: "bytes32"
						}
					],
					name: "ECDSAInvalidSignatureS",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "spender",
							type: "address"
						},
						{
							internalType: "uint256",
							name: "allowance",
							type: "uint256"
						},
						{
							internalType: "uint256",
							name: "needed",
							type: "uint256"
						}
					],
					name: "ERC20InsufficientAllowance",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "sender",
							type: "address"
						},
						{
							internalType: "uint256",
							name: "balance",
							type: "uint256"
						},
						{
							internalType: "uint256",
							name: "needed",
							type: "uint256"
						}
					],
					name: "ERC20InsufficientBalance",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "approver",
							type: "address"
						}
					],
					name: "ERC20InvalidApprover",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "receiver",
							type: "address"
						}
					],
					name: "ERC20InvalidReceiver",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "sender",
							type: "address"
						}
					],
					name: "ERC20InvalidSender",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "spender",
							type: "address"
						}
					],
					name: "ERC20InvalidSpender",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "uint256",
							name: "deadline",
							type: "uint256"
						}
					],
					name: "ERC2612ExpiredSignature",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "signer",
							type: "address"
						},
						{
							internalType: "address",
							name: "owner",
							type: "address"
						}
					],
					name: "ERC2612InvalidSigner",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "account",
							type: "address"
						},
						{
							internalType: "uint256",
							name: "currentNonce",
							type: "uint256"
						}
					],
					name: "InvalidAccountNonce",
					type: "error"
				},
				{
					inputs: [],
					name: "InvalidShortString",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "string",
							name: "str",
							type: "string"
						}
					],
					name: "StringTooLong",
					type: "error"
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "owner",
							type: "address"
						},
						{
							indexed: true,
							internalType: "address",
							name: "spender",
							type: "address"
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "value",
							type: "uint256"
						}
					],
					name: "Approval",
					type: "event"
				},
				{
					anonymous: false,
					inputs: [],
					name: "EIP712DomainChanged",
					type: "event"
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "from",
							type: "address"
						},
						{
							indexed: true,
							internalType: "address",
							name: "to",
							type: "address"
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "value",
							type: "uint256"
						}
					],
					name: "Transfer",
					type: "event"
				},
				{
					inputs: [],
					name: "DOMAIN_SEPARATOR",
					outputs: [
						{
							internalType: "bytes32",
							name: "",
							type: "bytes32"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "owner",
							type: "address"
						},
						{
							internalType: "address",
							name: "spender",
							type: "address"
						}
					],
					name: "allowance",
					outputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "spender",
							type: "address"
						},
						{
							internalType: "uint256",
							name: "value",
							type: "uint256"
						}
					],
					name: "approve",
					outputs: [
						{
							internalType: "bool",
							name: "",
							type: "bool"
						}
					],
					stateMutability: "nonpayable",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "account",
							type: "address"
						}
					],
					name: "balanceOf",
					outputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [],
					name: "decimals",
					outputs: [
						{
							internalType: "uint8",
							name: "",
							type: "uint8"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [],
					name: "eip712Domain",
					outputs: [
						{
							internalType: "bytes1",
							name: "fields",
							type: "bytes1"
						},
						{
							internalType: "string",
							name: "name",
							type: "string"
						},
						{
							internalType: "string",
							name: "version",
							type: "string"
						},
						{
							internalType: "uint256",
							name: "chainId",
							type: "uint256"
						},
						{
							internalType: "address",
							name: "verifyingContract",
							type: "address"
						},
						{
							internalType: "bytes32",
							name: "salt",
							type: "bytes32"
						},
						{
							internalType: "uint256[]",
							name: "extensions",
							type: "uint256[]"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "uint256",
							name: "amount",
							type: "uint256"
						}
					],
					name: "mint",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function"
				},
				{
					inputs: [],
					name: "name",
					outputs: [
						{
							internalType: "string",
							name: "",
							type: "string"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "owner",
							type: "address"
						}
					],
					name: "nonces",
					outputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "owner",
							type: "address"
						},
						{
							internalType: "address",
							name: "spender",
							type: "address"
						},
						{
							internalType: "uint256",
							name: "value",
							type: "uint256"
						},
						{
							internalType: "uint256",
							name: "deadline",
							type: "uint256"
						},
						{
							internalType: "uint8",
							name: "v",
							type: "uint8"
						},
						{
							internalType: "bytes32",
							name: "r",
							type: "bytes32"
						},
						{
							internalType: "bytes32",
							name: "s",
							type: "bytes32"
						}
					],
					name: "permit",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function"
				},
				{
					inputs: [],
					name: "symbol",
					outputs: [
						{
							internalType: "string",
							name: "",
							type: "string"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [],
					name: "totalSupply",
					outputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "to",
							type: "address"
						},
						{
							internalType: "uint256",
							name: "value",
							type: "uint256"
						}
					],
					name: "transfer",
					outputs: [
						{
							internalType: "bool",
							name: "",
							type: "bool"
						}
					],
					stateMutability: "nonpayable",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "from",
							type: "address"
						},
						{
							internalType: "address",
							name: "to",
							type: "address"
						},
						{
							internalType: "uint256",
							name: "value",
							type: "uint256"
						}
					],
					name: "transferFrom",
					outputs: [
						{
							internalType: "bool",
							name: "",
							type: "bool"
						}
					],
					stateMutability: "nonpayable",
					type: "function"
				}
			],
			inheritedFunctions: {
				allowance: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				approve: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				balanceOf: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				decimals: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				name: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				symbol: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				totalSupply: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				transfer: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				transferFrom: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				DOMAIN_SEPARATOR: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				eip712Domain: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				nonces: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				permit: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol"
			},
			deployedOnBlock: 1
		}
	},
	11155111: {
		Albums: {
			address: "0xBf947570A893958138E8e7F4264778afCa31D4E8",
			abi: [
				{
					inputs: [
						{
							internalType: "string",
							name: "_name",
							type: "string"
						},
						{
							internalType: "string",
							name: "_artist",
							type: "string"
						},
						{
							internalType: "string",
							name: "_imageCID",
							type: "string"
						}
					],
					name: "addAlbum",
					outputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					stateMutability: "nonpayable",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "uint256",
							name: "_albumId",
							type: "uint256"
						},
						{
							internalType: "uint256",
							name: "_songId",
							type: "uint256"
						}
					],
					name: "addSongToAlbum",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					name: "albums",
					outputs: [
						{
							internalType: "uint256",
							name: "id",
							type: "uint256"
						},
						{
							internalType: "string",
							name: "name",
							type: "string"
						},
						{
							internalType: "string",
							name: "artist",
							type: "string"
						},
						{
							internalType: "string",
							name: "imageCID",
							type: "string"
						}
					],
					stateMutability: "view",
					type: "function"
				}
			],
			inheritedFunctions: {},
			deployedOnBlock: 10228408
		},
		Songs: {
			address: "0x8F65DCcE84c7A52b03C3425B847d1e17D0e814ed",
			abi: [
				{
					inputs: [
						{
							internalType: "string",
							name: "_name",
							type: "string"
						},
						{
							internalType: "string",
							name: "_audioCID",
							type: "string"
						}
					],
					name: "addSong",
					outputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					stateMutability: "nonpayable",
					type: "function"
				},
				{
					inputs: [],
					name: "getAllSongs",
					outputs: [
						{
							components: [
								{
									internalType: "uint256",
									name: "id",
									type: "uint256"
								},
								{
									internalType: "string",
									name: "name",
									type: "string"
								},
								{
									internalType: "string",
									name: "audioCID",
									type: "string"
								}
							],
							internalType: "struct Songs.Song[]",
							name: "",
							type: "tuple[]"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [],
					name: "getTotalSongs",
					outputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					name: "songs",
					outputs: [
						{
							internalType: "uint256",
							name: "id",
							type: "uint256"
						},
						{
							internalType: "string",
							name: "name",
							type: "string"
						},
						{
							internalType: "string",
							name: "audioCID",
							type: "string"
						}
					],
					stateMutability: "view",
					type: "function"
				}
			],
			inheritedFunctions: {},
			deployedOnBlock: 10228409
		},
		Wavecoin: {
			address: "0x51F9706AF8cF334D69174277B2E347Beb4ADaAc6",
			abi: [
				{
					inputs: [],
					stateMutability: "nonpayable",
					type: "constructor"
				},
				{
					inputs: [],
					name: "ECDSAInvalidSignature",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "uint256",
							name: "length",
							type: "uint256"
						}
					],
					name: "ECDSAInvalidSignatureLength",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "bytes32",
							name: "s",
							type: "bytes32"
						}
					],
					name: "ECDSAInvalidSignatureS",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "spender",
							type: "address"
						},
						{
							internalType: "uint256",
							name: "allowance",
							type: "uint256"
						},
						{
							internalType: "uint256",
							name: "needed",
							type: "uint256"
						}
					],
					name: "ERC20InsufficientAllowance",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "sender",
							type: "address"
						},
						{
							internalType: "uint256",
							name: "balance",
							type: "uint256"
						},
						{
							internalType: "uint256",
							name: "needed",
							type: "uint256"
						}
					],
					name: "ERC20InsufficientBalance",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "approver",
							type: "address"
						}
					],
					name: "ERC20InvalidApprover",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "receiver",
							type: "address"
						}
					],
					name: "ERC20InvalidReceiver",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "sender",
							type: "address"
						}
					],
					name: "ERC20InvalidSender",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "spender",
							type: "address"
						}
					],
					name: "ERC20InvalidSpender",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "uint256",
							name: "deadline",
							type: "uint256"
						}
					],
					name: "ERC2612ExpiredSignature",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "signer",
							type: "address"
						},
						{
							internalType: "address",
							name: "owner",
							type: "address"
						}
					],
					name: "ERC2612InvalidSigner",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "account",
							type: "address"
						},
						{
							internalType: "uint256",
							name: "currentNonce",
							type: "uint256"
						}
					],
					name: "InvalidAccountNonce",
					type: "error"
				},
				{
					inputs: [],
					name: "InvalidShortString",
					type: "error"
				},
				{
					inputs: [
						{
							internalType: "string",
							name: "str",
							type: "string"
						}
					],
					name: "StringTooLong",
					type: "error"
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "owner",
							type: "address"
						},
						{
							indexed: true,
							internalType: "address",
							name: "spender",
							type: "address"
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "value",
							type: "uint256"
						}
					],
					name: "Approval",
					type: "event"
				},
				{
					anonymous: false,
					inputs: [],
					name: "EIP712DomainChanged",
					type: "event"
				},
				{
					anonymous: false,
					inputs: [
						{
							indexed: true,
							internalType: "address",
							name: "from",
							type: "address"
						},
						{
							indexed: true,
							internalType: "address",
							name: "to",
							type: "address"
						},
						{
							indexed: false,
							internalType: "uint256",
							name: "value",
							type: "uint256"
						}
					],
					name: "Transfer",
					type: "event"
				},
				{
					inputs: [],
					name: "DOMAIN_SEPARATOR",
					outputs: [
						{
							internalType: "bytes32",
							name: "",
							type: "bytes32"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "owner",
							type: "address"
						},
						{
							internalType: "address",
							name: "spender",
							type: "address"
						}
					],
					name: "allowance",
					outputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "spender",
							type: "address"
						},
						{
							internalType: "uint256",
							name: "value",
							type: "uint256"
						}
					],
					name: "approve",
					outputs: [
						{
							internalType: "bool",
							name: "",
							type: "bool"
						}
					],
					stateMutability: "nonpayable",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "account",
							type: "address"
						}
					],
					name: "balanceOf",
					outputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [],
					name: "decimals",
					outputs: [
						{
							internalType: "uint8",
							name: "",
							type: "uint8"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [],
					name: "eip712Domain",
					outputs: [
						{
							internalType: "bytes1",
							name: "fields",
							type: "bytes1"
						},
						{
							internalType: "string",
							name: "name",
							type: "string"
						},
						{
							internalType: "string",
							name: "version",
							type: "string"
						},
						{
							internalType: "uint256",
							name: "chainId",
							type: "uint256"
						},
						{
							internalType: "address",
							name: "verifyingContract",
							type: "address"
						},
						{
							internalType: "bytes32",
							name: "salt",
							type: "bytes32"
						},
						{
							internalType: "uint256[]",
							name: "extensions",
							type: "uint256[]"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "uint256",
							name: "amount",
							type: "uint256"
						}
					],
					name: "mint",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function"
				},
				{
					inputs: [],
					name: "name",
					outputs: [
						{
							internalType: "string",
							name: "",
							type: "string"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "owner",
							type: "address"
						}
					],
					name: "nonces",
					outputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "owner",
							type: "address"
						},
						{
							internalType: "address",
							name: "spender",
							type: "address"
						},
						{
							internalType: "uint256",
							name: "value",
							type: "uint256"
						},
						{
							internalType: "uint256",
							name: "deadline",
							type: "uint256"
						},
						{
							internalType: "uint8",
							name: "v",
							type: "uint8"
						},
						{
							internalType: "bytes32",
							name: "r",
							type: "bytes32"
						},
						{
							internalType: "bytes32",
							name: "s",
							type: "bytes32"
						}
					],
					name: "permit",
					outputs: [],
					stateMutability: "nonpayable",
					type: "function"
				},
				{
					inputs: [],
					name: "symbol",
					outputs: [
						{
							internalType: "string",
							name: "",
							type: "string"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [],
					name: "totalSupply",
					outputs: [
						{
							internalType: "uint256",
							name: "",
							type: "uint256"
						}
					],
					stateMutability: "view",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "to",
							type: "address"
						},
						{
							internalType: "uint256",
							name: "value",
							type: "uint256"
						}
					],
					name: "transfer",
					outputs: [
						{
							internalType: "bool",
							name: "",
							type: "bool"
						}
					],
					stateMutability: "nonpayable",
					type: "function"
				},
				{
					inputs: [
						{
							internalType: "address",
							name: "from",
							type: "address"
						},
						{
							internalType: "address",
							name: "to",
							type: "address"
						},
						{
							internalType: "uint256",
							name: "value",
							type: "uint256"
						}
					],
					name: "transferFrom",
					outputs: [
						{
							internalType: "bool",
							name: "",
							type: "bool"
						}
					],
					stateMutability: "nonpayable",
					type: "function"
				}
			],
			inheritedFunctions: {
				allowance: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				approve: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				balanceOf: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				decimals: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				name: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				symbol: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				totalSupply: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				transfer: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				transferFrom: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				DOMAIN_SEPARATOR: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				eip712Domain: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				nonces: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol",
				permit: "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol"
			},
			deployedOnBlock: 10124776
		}
	}
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
