#!/usr/bin/env python3
"""Seed or remove fake historical Ponder data for demos.

The script writes directly to Ponder's Postgres tables. It uses existing songs
and holders, then creates deterministic fake historical purchases, plays,
balances when needed, and royalty distributions.

Examples:
  python seed/seed_historical.py
  python seed/seed_historical.py --songs-per-holder 3 --months 6
  python seed/seed_historical.py --holder 0x...
  python seed/seed_historical.py --remove
"""

from __future__ import annotations

import argparse
import os
import subprocess
from dataclasses import dataclass


DEFAULT_DATABASE_URL = "postgres://wave3:wave3@localhost:5432/wave3"
DEFAULT_SCHEMA = "wave3"
DEFAULT_HOLDER = ""
DEFAULT_SONGS_PER_HOLDER = 5
DEFAULT_MONTHS = 6


@dataclass(frozen=True)
class Config:
    """Runtime options used as psql variables."""

    database_url: str
    schema: str
    holder: str
    songs_per_holder: int
    months: int
    remove: bool


def parse_args() -> Config:
    """Parse CLI flags and environment defaults."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--database-url", default=os.environ.get("DATABASE_URL", DEFAULT_DATABASE_URL))
    parser.add_argument("--schema", default=os.environ.get("DATABASE_SCHEMA", DEFAULT_SCHEMA))
    parser.add_argument("--holder", default=os.environ.get("HOLDER", DEFAULT_HOLDER))
    parser.add_argument(
        "--songs-per-holder",
        type=int,
        default=int(os.environ.get("SONGS_PER_HOLDER", os.environ.get("SONGS", DEFAULT_SONGS_PER_HOLDER))),
        help="Number of portfolio songs to seed per holder.",
    )
    parser.add_argument(
        "--months",
        type=int,
        default=int(os.environ.get("MONTHS", DEFAULT_MONTHS)),
        help="Number of historical months to generate.",
    )
    parser.add_argument(
        "--remove",
        action="store_true",
        help="Delete fake rows generated by this script.",
    )
    args = parser.parse_args()

    return Config(
        database_url=args.database_url,
        schema=args.schema,
        holder=args.holder,
        songs_per_holder=args.songs_per_holder,
        months=args.months,
        remove=args.remove,
    )


def run_psql(sql: str, config: Config) -> None:
    """Execute SQL through psql without requiring extra Python dependencies."""

    subprocess.run(
        [
            "psql",
            config.database_url,
            "-v",
            "ON_ERROR_STOP=1",
            "-v",
            f"schema={config.schema}",
            "-v",
            f"holder={config.holder}",
            "-v",
            f"songs={config.songs_per_holder}",
            "-v",
            f"months={config.months}",
        ],
        input=sql,
        text=True,
        check=True,
    )


def wrapped_sql(body: str) -> str:
    """Wrap seed/remove SQL in one transaction and silence Ponder live-query triggers.

    Some local Ponder schemas have table triggers that assume the live-query
    helper table exists. This script does not create permanent helper tables, so
    it disables user triggers only for the duration of this transaction.
    """

    return f"""
BEGIN;
SET LOCAL search_path TO :"schema", public;

ALTER TABLE song_purchases DISABLE TRIGGER USER;
ALTER TABLE song_share_balances DISABLE TRIGGER USER;
ALTER TABLE song_plays DISABLE TRIGGER USER;
ALTER TABLE royalty_distributions DISABLE TRIGGER USER;

{body}

ALTER TABLE royalty_distributions ENABLE TRIGGER USER;
ALTER TABLE song_plays ENABLE TRIGGER USER;
ALTER TABLE song_share_balances ENABLE TRIGGER USER;
ALTER TABLE song_purchases ENABLE TRIGGER USER;

COMMIT;
"""


REMOVE_SQL = r"""
DELETE FROM royalty_distributions WHERE id LIKE 'historical-%';
DELETE FROM song_plays WHERE id LIKE 'historical-%';
DELETE FROM song_purchases WHERE id LIKE 'historical-%';

DELETE FROM song_share_balances
WHERE last_transaction_hash = '0x' || lpad(md5('historical-balance-' || song_id || holder), 64, '0');

SELECT
  (SELECT count(*) FROM song_purchases WHERE id LIKE 'historical-%') AS purchases_left,
  (SELECT count(*) FROM song_plays WHERE id LIKE 'historical-%') AS plays_left,
  (SELECT count(*) FROM royalty_distributions WHERE id LIKE 'historical-%') AS royalties_left;
"""


SEED_SQL = r"""
DELETE FROM royalty_distributions WHERE id LIKE 'historical-%';
DELETE FROM song_plays WHERE id LIKE 'historical-%';
DELETE FROM song_purchases WHERE id LIKE 'historical-%';

DELETE FROM song_share_balances
WHERE last_transaction_hash = '0x' || lpad(md5('historical-balance-' || song_id || holder), 64, '0');

CREATE TEMP TABLE _hist_holders (holder text PRIMARY KEY);

INSERT INTO _hist_holders
SELECT DISTINCT lower(addr)
FROM (
  SELECT holder AS addr FROM song_share_balances WHERE parts > 0
  UNION
  SELECT buyer AS addr FROM song_purchases
  UNION
  SELECT holder AS addr FROM royalty_distributions WHERE id NOT LIKE 'historical-%'
) source
WHERE addr IS NOT NULL
  AND (nullif(:'holder', '') IS NULL OR lower(addr) = lower(:'holder'));

INSERT INTO _hist_holders
SELECT lower(coalesce(nullif(:'holder', ''), '0x70997970c51812dc3a010c7d01b50e0d17dc79c8'))
WHERE NOT EXISTS (SELECT 1 FROM _hist_holders);

CREATE TEMP TABLE _hist_songs AS
SELECT song_id
FROM songs
ORDER BY song_id;

CREATE TEMP TABLE _hist_positions AS
WITH ranked AS (
  SELECT
    h.holder,
    s.song_id,
    b.parts AS real_parts,
    b.id IS NULL AS synthetic_balance,
    row_number() OVER (
      PARTITION BY h.holder
      ORDER BY (b.id IS NULL), md5(h.holder || '-' || s.song_id)
    ) AS rank
  FROM _hist_holders h
  CROSS JOIN _hist_songs s
  LEFT JOIN song_share_balances b
    ON b.holder = h.holder
   AND b.song_id = s.song_id
   AND b.parts > 0
)
SELECT
  holder,
  song_id,
  row_number() OVER (PARTITION BY holder ORDER BY rank) AS n,
  coalesce(real_parts, 2 + (abs(hashtext(holder || '-' || song_id)) % 5))::bigint AS parts,
  synthetic_balance
FROM ranked
WHERE rank <= :songs;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM _hist_songs) THEN
    RAISE EXCEPTION 'No songs found in Ponder. Run seed_database.py first.';
  END IF;
END $$;

INSERT INTO song_purchases (id, song_id, buyer, parts, block_number, block_timestamp, transaction_hash)
SELECT
  'historical-buy-' || holder || '-' || song_id,
  song_id,
  holder,
  parts,
  9000000 + n,
  extract(epoch FROM date_trunc('month', now()) - ((:months - 1)::text || ' months')::interval + interval '3 days')::int,
  '0x' || lpad(md5('historical-buy-' || holder || '-' || song_id), 64, '0')
FROM _hist_positions;

INSERT INTO song_share_balances (
  id, song_id, holder, parts, first_acquired_timestamp, last_transfer_timestamp, last_transaction_hash
)
SELECT
  song_id || '-' || holder,
  song_id,
  holder,
  parts,
  extract(epoch FROM date_trunc('month', now()) - ((:months - 1)::text || ' months')::interval + interval '3 days')::int,
  extract(epoch FROM now() - interval '3 days')::int,
  '0x' || lpad(md5('historical-balance-' || song_id || holder), 64, '0')
FROM _hist_positions
WHERE synthetic_balance
ON CONFLICT (id) DO NOTHING;

WITH monthly AS (
  SELECT
    song_id,
    dense_rank() OVER (ORDER BY song_id) AS n,
    m,
    8 + ((song_id + m * 7) % 25) AS plays,
    extract(epoch FROM CASE
      WHEN m = 0 THEN now() - interval '3 days'
      ELSE date_trunc('month', now()) - (m::text || ' months')::interval + interval '10 days'
    END)::int AS ts
  FROM (SELECT DISTINCT song_id FROM _hist_positions) songs,
       generate_series(0, :months - 1) m
)
INSERT INTO song_plays (id, song_id, listener, block_number, block_timestamp, transaction_hash)
SELECT
  'historical-play-' || song_id || '-' || m || '-' || p,
  song_id,
  '0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc',
  9100000 + n * 1000 + m * 100 + p,
  ts,
  '0x' || lpad(md5('historical-play-' || song_id || '-' || m || '-' || p), 64, '0')
FROM monthly, generate_series(1, plays) p;

INSERT INTO royalty_distributions (id, song_id, holder, amount, block_number, block_timestamp, transaction_hash)
SELECT
  'historical-royalty-' || holder || '-' || song_id || '-' || m,
  song_id,
  holder,
  ((8 + ((song_id + m * 7) % 25)) * least(parts, 6) * 10000000000000000::bigint)::bigint,
  9200000 + n * 1000 + m,
  extract(epoch FROM CASE
    WHEN m = 0 THEN now() - interval '3 days'
    ELSE date_trunc('month', now()) - (m::text || ' months')::interval + interval '12 days'
  END)::int,
  '0x' || lpad(md5('historical-royalty-' || holder || '-' || song_id || '-' || m), 64, '0')
FROM _hist_positions, generate_series(0, :months - 1) m;

SELECT
  (SELECT count(*) FROM _hist_holders) AS holders,
  (SELECT count(*) FROM _hist_positions) AS positions,
  (SELECT count(*) FROM _hist_positions WHERE synthetic_balance) AS fake_balances,
  (SELECT count(DISTINCT song_id) FROM _hist_positions) AS songs,
  (SELECT count(*) FROM song_plays WHERE id LIKE 'historical-%') AS plays,
  (SELECT count(*) FROM royalty_distributions WHERE id LIKE 'historical-%') AS royalties;
"""


def main() -> None:
    """Run the requested seed operation."""

    config = parse_args()
    sql = REMOVE_SQL if config.remove else SEED_SQL
    run_psql(wrapped_sql(sql), config)


if __name__ == "__main__":
    main()
